spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:guilhermevicari19}:${DB_PASSWORD}@cluster0.rgs397m.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority
      auto-index-creation: true
    application:
      name: webflux-course
